// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package Di

import (
	"github.com/gedehariyogananda/pattern-golang/Controllers"
	"github.com/gedehariyogananda/pattern-golang/Repositories"
	"github.com/gedehariyogananda/pattern-golang/Services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func DIAuth(db *gorm.DB) *Controllers.AuthController {
	authRepository := Repositories.AuthRepositoryProvider(db)
	authService := Services.AuthServiceProvider(authRepository)
	authController := Controllers.AuthControllerProvider(authService)
	return authController
}
